// @vitest-environment jsdom
import React from 'react';
import { describe, it, expect, vi, beforeAll } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import { DiagramStudioView } from '../../components/DiagramStudioView';

// Mock Kroki service to prevent network calls in tests
vi.mock('../../services/krokiService', () => ({
  fetchKrokiSvg: vi.fn().mockResolvedValue('<svg><text>Mock Diagram SVG</text></svg>')
}));

// Mock Diagram AI Service
vi.mock('../../services/diagramAiService', () => ({
  generateDiagramWithAi: vi.fn().mockResolvedValue({
    code: 'graph TD; A-->B;',
    engine: 'mermaid',
    explanation: 'Sample diagram generated by AI'
  })
}));

beforeAll(() => {
  if (typeof window !== 'undefined') {
    window.HTMLElement.prototype.scrollIntoView = vi.fn();
  }
});

describe('DiagramStudioView Component Tests', () => {
  it('should render the Multi-Engine Diagram Studio without crashing', () => {
    render(<DiagramStudioView />);
    expect(screen.getAllByText(/Diagram Studio|Architecture/i).length).toBeGreaterThan(0);
  });

  it('should allow switching between categories', () => {
    render(<DiagramStudioView />);
    
    // Look for category pills or buttons
    const mathCategories = screen.getAllByText(/Mathematics & Calculus|Math/i);
    expect(mathCategories.length).toBeGreaterThan(0);
    fireEvent.click(mathCategories[0]);
  });

  it('should allow switching studio modes (Quick Deck, Copilot, Standard)', () => {
    render(<DiagramStudioView />);
    
    const copilotBtn = screen.getByTitle(/3-Column Multi-Turn Conversational Copilot/i);
    expect(copilotBtn).toBeDefined();
    fireEvent.click(copilotBtn);
  });
});
